---
- name: Setup BTRFS with Snapper on Fedora
  hosts: localhost
  connection: local
  become: yes
  vars:
    user: "{{ ansible_user_id }}"

  tasks:
    - name: Install required packages
      dnf:
        name:
          - snapper
          - btrfs-progs
          - inotify-tools
          - python3-dnf-plugin-snapper
        state: present

    - name: Create root configuration
      command: snapper -c root create-config /

    - name: Create home configuration
      command: snapper -c home create-config /home

    - name: Set root configuration
      command: snapper -c root set-config ALLOW_USERS={{ ansible_user_id }} SYNC_ACL=yes

    - name: Set home configuration  
      command: snapper -c home set-config ALLOW_USERS={{ ansible_user_id }} SYNC_ACL=yes

    - name: Set group ownership for root snapshots
      file:
        path: /.snapshots
        group: "{{ ansible_user_id }}"
        recurse: yes

    - name: Set group ownership for home snapshots
      file:
        path: /home/.snapshots
        group: "{{ ansible_user_id }}"
        recurse: yes