---
- name: Setup BTRFS with Snapper on Fedora
  hosts: localhost
  connection: local
  become: yes
  vars:
    user: "{{ ansible_user }}"

  tasks:
    - name: Install required packages
      dnf:
        name:
          - snapper
          - btrfs-progs
          - inotify-tools
          - python3-dnf-plugin-snapper
        state: present

    - name: Verify BTRFS is the filesystem for root
      command: findmnt -no FSTYPE /
      register: root_fs
      changed_when: false
      failed_when: root_fs.stdout != "btrfs"

    - name: Verify BTRFS is the filesystem for home
      command: findmnt -no FSTYPE /home
      register: home_fs
      changed_when: false
      failed_when: home_fs.stdout != "btrfs"

    - name: Create Snapper configuration for root
      command: snapper -c root create-config /

    - name: Create Snapper configuration for home
      command: snapper -c home create-config /home

    - name: Set Snapper configuration for root
      command: >
        snapper -c root set-config ALLOW_USERS={{ user }} SYNC_ACL=yes

    - name: Set Snapper configuration for home
      command: >
        snapper -c home set-config ALLOW_USERS={{ user }} SYNC_ACL=yes

    - name: Change ownership of root snapshots directory
      file:
        path: /.snapshots
        group: "{{ user }}"
        recurse: yes

    - name: Change ownership of home snapshots directory
      file:
        path: /home/.snapshots
        group: "{{ user }}"
        recurse: yes