---
- name: Install packages
  hosts: localhost
  become: yes  # This allows Ansible to use sudo

  vars:
    packages:
      - curl
      - wget
      - git
      - htop
      - zsh
      - tmux
      - vim
      - bat
      - make
      - tldr
      - thefuck
      - neovim
      - golang
      - python3-pip
      - powerline-fonts
      - fzf
      - jq
      - eza
      - kitty
      - unzip
      - p7zip
      - kitty
      - stow
      - kubernetes-client
      - helm
      - bind-utils
      - sipcalc
      - ripgrep
      - xz
      - zoxide
      - fastfetch
      - netcat
      - nmap
      - net-tools
      - gnome-tweaks
      - gnome-shell-extension-pop-shell
      - cabextract
      - xorg-x11-font-utils
      - fontconfig
      - xprop
      - keepassxc
      - yaru-icon-theme


  tasks:
    - name: Update package cache (for Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install packages on Debian/Ubuntu
      apt:
        name: "{{ packages }}"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install packages on RedHat/CentOS
      yum:
        name: "{{ packages }}"
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install packages on Fedora
      dnf:
        name: "{{ packages }}"
        state: present
      when: ansible_distribution == "Fedora"

    - name: Enable COPR repository for Zellij
      command: dnf copr enable -y varlad/zellij
      args:
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:varlad:zellij.repo
      when: ansible_distribution == "Fedora" or 
            (ansible_distribution == "CentOS" and ansible_distribution_major_version|int >= 8) or
            (ansible_distribution == "RedHat" and ansible_distribution_major_version|int >= 8)

    - name: Install Zellij
      dnf:
        name: zellij
        state: present
      when: ansible_distribution == "Fedora" or 
            (ansible_distribution == "CentOS" and ansible_distribution_major_version|int >= 8) or
            (ansible_distribution == "RedHat" and ansible_distribution_major_version|int >= 8)

    - name: Inform about unsupported distribution
      debug:
        msg: "This playbook is designed for Fedora, CentOS 8+, or RHEL 8+. Your current distribution ({{ ansible_distribution }}) may not be supported."
      when: ansible_distribution != "Fedora" and 
            not (ansible_distribution == "CentOS" and ansible_distribution_major_version|int >= 8) and
            not (ansible_distribution == "RedHat" and ansible_distribution_major_version|int >= 8)

