---
- name: Install packages
  hosts: localhost
  become: yes  # This allows Ansible to use sudo

  vars:
    packages:
      - curl
      - wget
      - git
      - htop
      - zsh
      - tmux
      - vim
      - bat
      - make
      - tldr
      - thefuck
      - neovim
      - golang
      - python3-pip
      - powerline-fonts
      - fzf
      - jq
      - eza
      - unzip
      - p7zip
      - kitty
      - stow
      - kubernetes-client
      - helm
      - bind-utils
      - sipcalc
      - ripgrep
      - xz
      - zoxide
      - fastfetch
      - netcat
      - nmap
      - net-tools
      - gnome-tweaks
      - gnome-shell-extension-pop-shell
      - cabextract
      - xorg-x11-font-utils
      - fontconfig
      - xprop
      - keepassxc

  tasks:
    - name: Inform about unsupported distribution
      debug:
        msg: "This playbook is designed for Fedora, CentOS 8+, or RHEL 8+. Your current distribution ({{ ansible_distribution }}) may not be supported."
      when: ansible_distribution != "Fedora" and 
            not (ansible_distribution == "CentOS" and ansible_distribution_major_version|int >= 8) and
            not (ansible_distribution == "RedHat" and ansible_distribution_major_version|int >= 8)

    - name: Install packages on Fedora
      block:
        - name: Install package
          dnf:
            name: "{{ item }}"
            state: present
          loop: "{{ packages }}"
      when: ansible_distribution == "Fedora"

    - name: Enable COPR repository for Zellij
      command: dnf copr enable -y varlad/zellij
      args:
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:varlad:zellij.repo
      when: ansible_distribution == "Fedora" or 
            (ansible_distribution == "CentOS" and ansible_distribution_major_version|int >= 8) or
            (ansible_distribution == "RedHat" and ansible_distribution_major_version|int >= 8)

    - name: Install Zellij
      dnf:
        name: zellij
        state: present
      when: ansible_distribution == "Fedora" or 
            (ansible_distribution == "CentOS" and ansible_distribution_major_version|int >= 8) or
            (ansible_distribution == "RedHat" and ansible_distribution_major_version|int >= 8)

    - name: Import Microsoft GPG key
      rpm_key:
        key: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add VSCode repository
      copy:
        content: |
          [code]
          name=Visual Studio Code
          baseurl=https://packages.microsoft.com/yumrepos/vscode
          enabled=1
          gpgcheck=1
          gpgkey=https://packages.microsoft.com/keys/microsoft.asc
        dest: /etc/yum.repos.d/vscode.repo

    - name: Update DNF cache
      dnf:
        update_cache: yes

    - name: Install VSCode
      dnf:
        name: code
        state: present

    - name: Add Lens repository
      command: dnf config-manager --add-repo https://downloads.k8slens.dev/rpm/lens.repo
      args:
        creates: /etc/yum.repos.d/lens.repo

    - name: Install Lens
      dnf:
        name: lens
        state: present